(require :cl-glfw)
;(require :cl-glfw-opengl-core)
(require :cl-glfw-opengl-version_1_1)
(require :cl-glfw-glu)

(let ((rot 0))
 (defun draw ()
   (gl:translate-f 0 14 0)
   (gl:rotate-f rot 0 0 1)
   (if (< rot 360)
       (incf rot)
       (setf rot 0))
   (gl:line-width 3)
   (gl:with-begin gl:+lines+
     (gl:color-3ub 255 150 30) (gl:vertex-3f 0 0 0) (gl:vertex-3f 5 0 0)
     (gl:color-3ub 100 255 30) (gl:vertex-3f 0 0 0) (gl:vertex-3f 0 5 0)
     (gl:color-3ub 20 100 255) (gl:vertex-3f 0 0 0) (gl:vertex-3f 0 0 5))
   (gl:color-3ub 255 255 255)
   (gl:with-begin gl:+triangle-strip+
     (loop for (x y z) in '((0 0 1) (0 1 0) (1 0 0)
			    (1 1 1) (0 0 1) (0 1 0)) do
	  (gl:vertex-3f x y z)))))

(glfw:do-window (:title "bla" :width 512 :height 512)
    ()
  (when (eql (glfw:get-key glfw:+key-esc+) glfw:+press+)
    (return-from glfw::do-open-window))
  (destructuring-bind (w h) (glfw:get-window-size)
    (setf h (max h 1))
    (gl:viewport 0 0 w h)
    (gl:clear gl:+color-buffer-bit+)
    (gl:matrix-mode gl:+projection+)
    (gl:load-identity)
    (glu:perspective 65 (/ w h) 1 100)
    (gl:matrix-mode gl:+modelview+)
    (gl:load-identity)
    (glu:look-at 0 1 0
    		 0 20 0
		 0 0 1 )
    (draw)))